# Generated by Django 4.2.11 on 2025-12-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    def seed_plans(apps, schema_editor):
        PlanFeature = apps.get_model("core", "PlanFeature")
        Plan = apps.get_model("core", "Plan")
        Subscription = apps.get_model("core", "Subscription")

        feature_specs = {
            "inventory": "Inventario y compras",
            "sales": "Ventas y órdenes",
            "orders": "Checkout",
            "pos": "POS",
            "reports": "Reportes",
            "user_management": "Gestión de usuarios",
            "branches_unlimited": "Sucursales ilimitadas",
        }
        features = {}
        for code, label in feature_specs.items():
            feature, _ = PlanFeature.objects.get_or_create(code=code, defaults={"label": label})
            features[code] = feature

        plan_specs = [
            ("BASICO", "Plan Básico", 1, ["inventory", "sales", "orders", "pos", "user_management"]),
            ("ESTANDAR", "Plan Estándar", 3, ["inventory", "sales", "orders", "pos", "reports", "user_management"]),
            (
                "PREMIUM",
                "Plan Premium",
                None,
                ["inventory", "sales", "orders", "pos", "reports", "user_management", "branches_unlimited"],
            ),
        ]
        plans = {}
        for code, name, branch_limit, feature_codes in plan_specs:
            plan, _ = Plan.objects.get_or_create(
                code=code,
                defaults={"name": name, "branch_limit": branch_limit, "monthly_price": 0},
            )
            plan.name = name
            plan.branch_limit = branch_limit
            plan.is_active = True
            plan.save()
            plan.features.set([features[fc] for fc in feature_codes])
            plans[code] = plan

        # Migrar suscripciones antiguas
        for subscription in Subscription.objects.all():
            plan_code = getattr(subscription, "plan_name", None) or "BASICO"
            subscription.plan = plans.get(plan_code)
            if getattr(subscription, "active", False):
                subscription.status = "active"
            subscription.save()

    operations = [
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "branch_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Límite de sucursales (vacío para ilimitado)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True, related_name="plans", to="core.planfeature"
                    ),
                ),
            ],
            options={
                "ordering": ["monthly_price", "name"],
            },
        ),
        migrations.AddField(
            model_name="company",
            name="administrators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Usuarios con rol de administrador asociados a la empresa.",
                related_name="admin_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Activa"),
                    ("cancelled", "Cancelada"),
                    ("expired", "Expirada"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="core.plan",
            ),
        ),
        migrations.RunPython(seed_plans, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="subscription",
            name="active",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="plan_name",
        ),
    ]
