# Generated by Django 5.2.5 on 2025-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Compra'), ('SALE', 'Venta'), ('ADJUST', 'Ajuste'), ('TRANSFER', 'Traspaso')], max_length=20),
        ),
    ]
